"""Reviewer — generate human-reviewable patch reports."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from roxy.config.paths import roxy_home
from roxy.evolution.proposal import EvolutionProposal
from roxy.evolution.runner import TestReport


class EvolutionReviewer:
    """Generates patch review reports for human decision."""

    def __init__(self):
        self._reports_dir = roxy_home() / "evolution" / "runs"

    def run_dir(self, proposal_id: str) -> Path:
        d = self._reports_dir / proposal_id
        d.mkdir(parents=True, exist_ok=True)
        return d

    def generate(
        self,
        proposal: EvolutionProposal,
        patch_result: dict[str, Any],
        test_report: TestReport,
        diff: str,
        eval_compare: dict | None = None,
    ) -> str:
        """Generate and save a patch report. Returns markdown string."""
        now = datetime.now(timezone.utc).isoformat()
        status = "tested" if test_report.all_passed else "test-failed"

        lines = [
            f"# Evolution Patch Report",
            "",
            f"**Proposal**: {proposal.id}",
            f"**Target**: {proposal.target}",
            f"**Branch**: `evolve/{proposal.id}`",
            f"**Status**: {status}",
            f"**Generated**: {now[:19]}",
            "",
            "## Summary",
            proposal.proposed_change,
            "",
            "## Files Changed",
        ]
        for f in patch_result.get("files_changed", []):
            lines.append(f"- `{f}`")
        lines.append("")

        if diff:
            lines.append("## Diff")
            lines.append("```diff")
            lines.append(diff[:5000])
            lines.append("```")
            lines.append("")

        lines.append("## Test Results")
        for tr in test_report.results:
            icon = "[green]✓[/green]" if tr.passed else "[red]✗[/red]"
            lines.append(f"- {icon} `{tr.command}` (exit {tr.exit_code})")
            if not tr.passed and tr.stderr:
                lines.append(f"  ```")
                lines.append(f"  {tr.stderr[:300]}")
                lines.append(f"  ```")
        lines.append("")

        if eval_compare:
            lines.append("## Eval Compare")
            lines.append(f"- Baseline avg: {eval_compare.get('baseline_avg', '—')}")
            lines.append(f"- Candidate avg: {eval_compare.get('candidate_avg', '—')}")
            lines.append(f"- Delta: {eval_compare.get('delta', '—')}")
            lines.append(f"- Improvements: {len(eval_compare.get('improvements', []))}")
            lines.append(f"- Regressions: {len(eval_compare.get('regressions', []))}")
            lines.append("")

        lines.append("## Risk")
        lines.append(f"**Level**: {proposal.risk}")
        lines.append(proposal.risk_rationale)
        lines.append("")

        lines.append("## Rollback")
        lines.append(f"```bash")
        lines.append(f"git checkout main")
        lines.append(f"git branch -D evolve/{proposal.id}")
        lines.append(f"```")
        lines.append("")

        lines.append("## Human Decision")
        lines.append("```")
        lines.append("[ ] Approve — merge to main")
        lines.append("[ ] Reject — delete branch")
        lines.append("[ ] Iterate — keep branch, refine patch")
        lines.append("```")
        lines.append("")
        lines.append(f"*Generated by Roxy Evolution Reviewer — {now[:19]}*")

        report_md = "\n".join(lines)

        # Save to disk
        out = self.run_dir(proposal.id) / "report.md"
        out.write_text(report_md, encoding="utf-8")

        return report_md
