"""Tests for ResearchDigest 2.0 — structured reports."""

from pathlib import Path

from roxy.knowledge.schema import KnowledgeEntry
from roxy.knowledge.store import KnowledgeStore
from roxy.research.digest import ResearchDigest


class TestResearchDigest:
    def test_empty_kb_returns_zero_entries(self, tmp_path: Path):
        store = KnowledgeStore(db_path=tmp_path / "test.db")
        store.init_db()
        dg = ResearchDigest(store)
        result = dg.generate(days=7)
        assert result["entry_count"] == 0

    def test_digest_has_report_md(self, tmp_path: Path):
        store = KnowledgeStore(db_path=tmp_path / "test.db")
        store.init_db()
        store.insert_entry(KnowledgeEntry(
            title="Recent Article", canonical_url="https://example.com/recent",
            content_plain="Recent research finding.", collected_via="rss",
        ))
        dg = ResearchDigest(store)
        result = dg.generate(days=30)
        assert result["entry_count"] >= 1
        assert "Recent Article" in result["report_md"]
        assert "# Roxy Research Digest" in result["report_md"]
        assert "## Overview" in result["report_md"]

    def test_groups_by_source(self, tmp_path: Path):
        store = KnowledgeStore(db_path=tmp_path / "test.db")
        store.init_db()
        store.insert_entry(KnowledgeEntry(
            title="RSS Item", canonical_url="https://a.com/rss",
            content_plain="x", collected_via="rss",
        ))
        store.insert_entry(KnowledgeEntry(
            title="Web Item", canonical_url="https://a.com/web",
            content_plain="y", collected_via="web",
        ))
        dg = ResearchDigest(store)
        result = dg.generate(days=30, group_by="source")
        assert len(result["groups"]) == 2
        assert "rss" in result["groups"]
        assert "web" in result["groups"]

    def test_groups_by_date(self, tmp_path: Path):
        store = KnowledgeStore(db_path=tmp_path / "test.db")
        store.init_db()
        store.insert_entry(KnowledgeEntry(
            title="Item", canonical_url="https://a.com/1",
            content_plain="x", collected_via="rss",
        ))
        dg = ResearchDigest(store)
        result = dg.generate(days=30, group_by="date")
        assert result["group_by"] == "date"
        assert len(result["groups"]) >= 1

    def test_groups_by_tag(self, tmp_path: Path):
        store = KnowledgeStore(db_path=tmp_path / "test.db")
        store.init_db()
        _, eid = store.insert_entry(KnowledgeEntry(
            title="Tagged", canonical_url="https://a.com/t",
            content_plain="x", collected_via="rss",
        ))
        store._add_tags(eid, ["ai", "science"])
        dg = ResearchDigest(store)
        result = dg.generate(days=30, group_by="tag")
        assert result["group_by"] == "tag"
        assert "ai" in result["groups"] or "science" in result["groups"]

    def test_filter_by_source(self, tmp_path: Path):
        store = KnowledgeStore(db_path=tmp_path / "test.db")
        store.init_db()
        store.insert_entry(KnowledgeEntry(
            title="RSS Only", canonical_url="https://a.com/1",
            content_plain="rss entry", collected_via="rss",
        ))
        store.insert_entry(KnowledgeEntry(
            title="Web Item", canonical_url="https://a.com/2",
            content_plain="web entry", collected_via="web",
        ))
        dg = ResearchDigest(store)
        result = dg.generate(days=30, collected_via="rss")
        assert result["entry_count"] >= 1
        assert "RSS Only" in result["report_md"]

    def test_report_md_has_sections(self, tmp_path: Path):
        store = KnowledgeStore(db_path=tmp_path / "test.db")
        store.init_db()
        store.insert_entry(KnowledgeEntry(
            title="Article", canonical_url="https://a.com/1",
            content_plain="content", collected_via="rss",
        ))
        dg = ResearchDigest(store)
        result = dg.generate(days=30)
        md = result["report_md"]
        assert "## Overview" in md
        assert "## Source:" in md or "## Source" in md
        assert "## Key Entries" in md
        assert "## Links" in md
        assert "Generated by Roxy" in md

    def test_write_report_to_file(self, tmp_path: Path):
        store = KnowledgeStore(db_path=tmp_path / "test.db")
        store.init_db()
        store.insert_entry(KnowledgeEntry(
            title="File Test", canonical_url="https://a.com/file",
            content_plain="test", collected_via="manual",
        ))
        dg = ResearchDigest(store)
        result = dg.generate(days=30)

        out = tmp_path / "digest.md"
        dg.write_report(result, out)
        assert out.exists()
        content = out.read_text(encoding="utf-8")
        assert "File Test" in content
        assert "# Roxy Research Digest" in content
